name: Build Electron App

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Build Electron app (Windows)
      if: matrix.os == 'windows-latest'
      run: npx electron-builder --win
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        EP_DRAFT: false
        EP_PRE_RELEASE: false
        
    - name: Build Electron app (macOS)
      if: matrix.os == 'macos-latest'
      run: npx electron-builder --mac
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        EP_DRAFT: false
        EP_PRE_RELEASE: false
        
    - name: Build Electron app (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npx electron-builder --linux
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        EP_DRAFT: false
        EP_PRE_RELEASE: false
        
    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: wfm-scanner-windows
        path: |
          dist/*.exe
          dist/win-unpacked/
        retention-days: 30
        
    - name: Upload macOS artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: wfm-scanner-macos
        path: |
          dist/*.dmg
          dist/mac/
        retention-days: 30
        
    - name: Upload Linux artifacts
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: wfm-scanner-linux
        path: |
          dist/*.AppImage
          dist/linux-unpacked/
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          wfm-scanner-windows/**/*
          wfm-scanner-macos/**/*
          wfm-scanner-linux/**/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}